### ISSUE TITLE
Add a list of dead keys to each language to remove them from the accuracy calculation

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#1920]

**Comment by Vermoot** [comment]
For French, these would be `'`, `"`, `^` and `` ` ``. I believe that's it, but I can't say for sure.

**Comment by MrExcaliburBr** [comment]
The only one that I'm completely shure about is Portuguese (Brazillian variant). That is:
``^``, `` ` ``, ``~`` and ``'`` (and `` ¨ ``, but it isn't in our language, only kept for international purposes).
But instead of separating them by language, wouldn't it be easier to just list all dead keys, regardless of the language? Most languages mainly use normal alphas, and some have common accented characters as their own key ( like ç on ABNT keyboards and  ä, ö, and ü in german ones ), and, from my experience, all dead keys function the same, because it is possible to type accented characters that aren't in your language ( like ñ or ć in my case ).

**Comment by mbvs** [comment]
Would also suggest to ignore all dead keys, cause they are not language dependent but keyboard layout dependent. For example I use standard US Ansi Layout (which has no dead keys at all) and US Ansi International Layout which has '"^`~ as dead keys. Should be pretty simple cause there is a KeyboardEvent key for it: [https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key)

**Comment by Miodec** [comment]
Since then we've added a `composing` event check, which makes this improvement not needed.
