### ISSUE TITLE
Use select2 for result filters and funbox in account page

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#2537]

**Comment by roshaan005** [comment]
could I get some more info regarding this issue?

**Comment by Miodec** [comment]
Hmm, my idea when creating this issue was that this seems like its taking a lot of space 
![image](https://user-images.githubusercontent.com/13181393/162046489-9be4b5f9-2aea-4ccf-b92b-df57124e64b8.png)

and it would be better to use something like this:

![image](https://user-images.githubusercontent.com/13181393/162046572-c631a328-885a-4a42-b1d8-dca291d37ed3.png)


But, I'm not sure if it really matters. The advanced filters are out of the way most of the time. So, I don't know.
