### ISSUE TITLE
Remove swapEscAndTab, replace quickTab with quickRestart

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#3130]
Quick restart will have 3 options: off, tab and esc. If set to esc commandline can only be accessed with ctrl shift p. Make sure to update the keytips. Make sure to automatically set quick restart to tab if quicktab is enabled. Make sure to set quick restart to esc if swap esc and tab was enabled.

**Comment by devkennyy** [comment]
I'd like to give this a shot!

**Comment by willdhorn** [comment]
Should a similar option be added for the command line? Either that or making the command line key bindable? As someone who previously had Esc and Tab swapped, this feature feels like a strict downgrade (though I understand the purpose was to fix #3051). On Mac ctrl+shft+p is annoying and awkward since it's not used for hotkeys that much, and on windows I don't even know if you could open the command line on firefox since ctrl+shft+p opens a private window. 

Personally I would prefer to bring back swapEscAndTab, but since quickRestart is a useful fix to the other issue, and it obviously doesn't make sense to have both, I figured that making the command line key bindable is the next solution.

**Comment by Miodec** [comment]
> On Mac ctrl+shft+p is annoying and awkward since it's not used for hotkeys that much, and on windows I don't even know if you could open the command line on firefox since ctrl+shft+p opens a private window.

You can also use `cmd+shift+p` just fyi

**Comment by willdhorn** [comment]
> You can also use cmd+shift+p just fyi

Right, but that opens a private window since I'm using firefox
