### ISSUE TITLE
Pace caret disappears with "plus two" option

### ISSUE THREAD

**Issue by wilderjds** [monkeytypegame/monkeytype#4023]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

wilder-colemak

### Current Behavior

Turn on pace caret and the "plus two" feature (most likely this also happens in other similar situations)
As soon as the pace caret goes beyond words that are visible, it disappears and never comes back even if I "catch up" with it 

### Environment

- OS: Linux
- Browser: WebEngine based (Faikon)
- Browser Version:

**Comment by Miodec** [comment]
Im afraid thats a limitation of `plus_one` / `plus_two` funboxes and the pace caret. The pace caret relies on elements existing to move between them and accurately display the required position to achieve the desired speed.

Because those funboxes limit the word generation, instead of just making the words invisible, the pace caret just runs out of elements.
