### ISSUE TITLE
Custom text saved with pipe delimiter isnt loaded correctly

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#4534]

**Comment by sanidhyas3s** [comment]
More details about the issue and steps to replicate would be helpful. I would like to work on this.
@Miodec

**Comment by Miodec** [comment]
If you enable pipe delimiter, then save the text `this is|a test` as custom text, when you load that text, it is incorrectly loaded as `this|is|a|test`

**Comment by sanidhyas3s** [comment]
The way it works right now, is that when saving it breaks the text into 'space' separated words, and then joins them with the delimiter (`|` if pipe is enabled, space otherwise). Do we want to replace space with `|` at all? Because when saving `|` is considered as any other character.

So, if the expected correct behavior is simply keeping spaces, spaces and not replacing them with `|`, basically if you want to load a pipe-delimited text, you must also save a pipe-delimited text. If this is what is needed then this is just a simple fix, I will make a MR with that done. @Miodec 

This is more of a UX question at this point, I have never used the pipe-delimiter, so can't comment.

**Comment by Miodec** [comment]
> @Miodec Why would you want to use Pipe character when you are going to use it as a delimiter?

Dont understand the question sorry
