### ISSUE TITLE
Quote Leaderboards

### ISSUE THREAD

**Issue by NotGate** [monkeytypegame/monkeytype#462]
Quote leaderboards would be a boon to monkeytype's popularity and competitiveness. 

After each quote test, a leaderboard could be printed below your results that show your placement relative to everyone else.

```
1 | taran  | 420 WPM
2 | shazzy | 410 WPM
3 | foggy  | 400 WPM
...
257 | ze_or   | 161 WPM
258 | notgate | 160 WPM
```

The leaderboard could go below or above these buttons and only needs to show a few rows to give you an idea of your relative position. 
![image](https://user-images.githubusercontent.com/32425311/97055117-fe14e200-153a-11eb-87d8-6ebf9c3638d7.png)

I think if this is added, then retrying should be allowed for quotes. Currently retrying a quote doesn't accept any new PBs.

**Comment by TheeKevin** [comment]
Adding to this idea we should have daily leaderboards so that people can compete easier instead of the top 100 being over 200 wpm. We should also have subsections inside the quote leaderboard for quote length as some people can burst in speed well while others have the ability to maintain a high speed for long quotes.

**Comment by QuickDevV** [comment]
This would be amazing if it was there lol :)

**Comment by Miodec** [comment]
Sorry guys, its not really feasible at the moment. We *miight* come back to it at some point.
