### ISSUE TITLE
When stop on word disables confidence mode, make sure confidence mode state is saved

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#4638]

**Comment by sanidhyas3s** [comment]
Actually setting any one resets the other to `off`, what are thinking of as a solution for this. Maybe merge the two since they depend on each other, and just making the user select one of the two (5 options basically, both off, word, letter, confidence mode on, max confidence mode). Another way would be sort of greying out the other setting when the user sets one, but then we would have them greying out when the other is set (just with remembering the state they were greyed out in) but still how exactly will they get back from greyed state to normal state becomes a question. 

Making them combined in some way is what I suggest so that the behavior is implicitly implied and not something that the user experiences directly.

@Miodec

**Comment by Miodec** [comment]
And to respond to the combining suggestion: i dont really like it, i think they are not simmilar enough to be combined into one setting. Yes, they are exclusive, but i dont think it would make sense to combine from a UX perspective.

**Comment by mohanadft** [comment]
Hi, could you give me an example from the website?

**Comment by mohanadft** [comment]
I've just tested it out locally, the behavior sounds fine and the bug didn't occur

**Comment by mohanadft** [comment]
Locally, the `confidenceMode` behavior in localstorage:
`max` -> `off`
and after reload, it remains `off` the same as before.

but when I tried it in the original website, there is some code that overwrite the value to the previous chosen one.
btw: I've not setup my backend yet.

**Comment by Miodec** [comment]
> I've just tested it out locally, the behavior sounds fine and the bug didn't occur

It will only happen if youre using an account.

**Comment by ayushnau** [comment]
@Miodec cant see the bug even if I am using an account. the Confidence value is remaning same.
