### ISSUE TITLE
Autoswitch theme causing the footer theme indicator to show wrong theme

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#4659]

**Comment by sanidhyas3s** [comment]
Steps to replicate?

**Comment by sanidhyas3s** [comment]
Rather than just fixing the footer thing, which should be easy, lets make the overall behavior more consistent. So currently, when you switch on the Auto Switch, the theme changes according to that, but you still have a theme selected normally (which you will switch back to if you turn off auto switch) but we turn on auto-switch and then change the theme manually (the theme will appear changed) but on reload the theme switches back to the auto switch one, so as a fix I am proposing that the auto-switch turns off whenever someone changes the theme over it, maybe with a message that it turned off as a result of you changing the theme manually. I hope I was able to explain the concern and the solution.

@Miodec

**Comment by sanidhyas3s** [comment]
Also the behavior between custom theme and auto-switch theme seems counter-intuitive really, switching on one should switch off the other simply, basically higher priority given to the one modified later. The specific edge cases are not handled cleanly.

For example, the following results shouldn't be that way:

1. Switch to custom theme.
2. Turn on auto-switch (has no effect)
3. Switch back to a preset theme from custom (theme changes to the preset theme)
4. Reload (theme changes to the auto-switch theme)
This is not quite correct in an obvious manner as reloading should never change the theme.

So, rather than pointing out these things one by one in comments, I will make a MR with the changes suggested directly.

**Comment by Miodec** [comment]
> so as a fix I am proposing that the auto-switch turns off whenever someone changes the theme over it, maybe with a message that it turned off as a result of you changing the theme manually.

Yeah, that makes sense

**Comment by Miodec** [comment]
> switching on one should switch off the other simply, basically higher priority given to the one modified later.

Yeah that makes sense

> So, rather than pointing out these things one by one in comments, I will make a PR with the changes suggested directly.

Sounds good, looking forward.

**Comment by sanidhyas3s** [comment]
@Miodec Done!
